#!/usr/bin/env python3
"""Write .agents/skills/README.md: a Mermaid graph of how skills relate.

The project is HARNESS_ROOT, or the working directory when it is unset. When the
project is not this harness, the core group shows a fixed node for the core plugin and
only the core skills that project skills declare in metadata.related; body
citations only link project skills, and only the project draws arrows, so a core release that adds or
relates core skills leaves the project graph unchanged.
A skill that lists metadata.related draws solid arrows to those skills. A skill
without that list draws dotted arrows to the skills its body cites: names between
backticks in prose, or names in a Mermaid diagram.
--check exits 1 when the README differs from what this script would write.
"""

from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

README = Path(".agents") / "skills" / "README.md"


def repo_root(start: Path) -> Path:
    for path in (start, *start.parents):
        if (path / ".agents" / "config.yml").is_file():
            return path
    raise SystemExit(".agents/config.yml not found")


@dataclass
class Skill:
    name: str
    layer: str
    related: list[str] | None
    body: str
    edges: set[str] = field(default_factory=set)
    declared: bool = False
    extends: str | None = None
    node_id: str = ""


def config_value(roots: list[Path], section: str, key: str) -> str:
    for root in roots:
        data = yaml.safe_load((root / ".agents" / "config.yml").read_text(encoding="utf-8")) or {}
        value = (data.get(section) or {}).get(key)
        if value is not None:
            return str(value)
    raise SystemExit(f"{section}.{key} is missing from .agents/config.yml")


def read_skills(root: Path, layer: str) -> list[Skill]:
    skills: list[Skill] = []
    folder = root / ".agents" / "skills"
    if not folder.is_dir():
        return skills
    for path in sorted(folder.glob("*/SKILL.md")):
        text = path.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            continue
        end = text.find("\n---", 4)
        front = yaml.safe_load(text[4:end]) or {}
        metadata = front.get("metadata") or {}
        related = metadata.get("related")
        skills.append(
            Skill(
                name=str(front.get("name") or path.parent.name),
                layer=layer,
                related=[str(item) for item in related] if isinstance(related, list) else None,
                body=text[end + 4 :],
                extends=str(metadata["extends"]) if metadata.get("extends") else None,
            )
        )
    return skills


def link(skills: list[Skill], cite_layers: set[str] | None = None) -> None:
    names = {skill.name for skill in skills}
    citable = {skill.name for skill in skills if cite_layers is None or skill.layer in cite_layers}
    for skill in skills:
        if skill.related is not None:
            skill.declared = True
            skill.edges = {item for item in skill.related if item in names and item != skill.name}
        else:
            skill.edges = cited_names(skill.body, citable) - {skill.name}


MERMAID_BLOCK = re.compile(r"^```mermaid[^\n]*\n(.*?)^```", re.M | re.S)
BACKTICKED = re.compile(r"`([a-z0-9][a-z0-9-]*)`")


def cited_names(body: str, candidates: set[str]) -> set[str]:
    """Skill names cited in a body: between backticks in prose, or as a name in a Mermaid diagram."""
    found = set(BACKTICKED.findall(MERMAID_BLOCK.sub("", body))) & candidates
    for block in MERMAID_BLOCK.findall(body):
        found.update(
            name
            for name in candidates
            if re.search(r"(?<![a-z0-9-])" + re.escape(name) + r"(?![a-z0-9-])", block)
        )
    return found


def node(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "_", name)


CORE_MARKER = 'core_plugin(["core"])'


def render(
    skills: list[Skill], groups: list[tuple[str, str]], direction: str, note: str = "", marker: bool = False
) -> str:
    lines = [
        "---",
        "locale: en",
        "---",
        "",
        "# Skills",
        "",
        "<!-- Generated by skill-graph from jimmyandrade/harness. Do not edit by hand. -->",
        "",
        "Solid arrows come from `metadata.related`. Dotted arrows are skills cited in the body of a skill that does not declare `metadata.related` yet." + note,
        "",
        "```mermaid",
        f"flowchart {direction}",
    ]
    for layer, title in groups:
        members = [skill for skill in skills if skill.layer == layer]
        show_marker = marker and layer == "core"
        if not members and not show_marker:
            continue
        lines.append(f'  subgraph {layer}["{title}"]')
        if show_marker:
            lines.append(f"    {CORE_MARKER}")
        lines.extend(f'    {skill.node_id or node(skill.name)}["{skill.name}"]' for skill in members)
        lines.append("  end")
    for skill in skills:
        arrow = "-->" if skill.declared else "-.->"
        lines.extend(f"  {skill.node_id or node(skill.name)} {arrow} {node(target)}" for target in sorted(skill.edges))
    for skill in skills:
        if skill.layer == "project" and skill.extends:
            lines.append(f"  {node(skill.name)} -- extends --> {node(skill.name)}_core")
    lines.append("```")
    return "\n".join(lines) + "\n"


def build(project: Path, core: Path) -> str:
    roots = list(dict.fromkeys([project, core]))
    direction = config_value(roots, "mermaid", "flowchart_direction")
    if project == core:
        skills = read_skills(core, "core")
        groups = [("core", "Core")]
    else:
        organization = config_value(roots, "organization", "name")
        skills = read_skills(project, "project") + read_skills(core, "core")
        groups = [("project", organization), ("core", "Core")]
        link(skills, cite_layers={"project"})
        cited = {target for skill in skills if skill.layer == "project" for target in skill.edges}
        extended = {skill.name for skill in skills if skill.layer == "project" and skill.extends}
        skills = [skill for skill in skills if skill.layer == "project" or skill.name in cited | extended]
        for skill in skills:
            if skill.layer == "core":
                skill.edges = set()
                if skill.name in extended:
                    skill.node_id = node(skill.name) + "_core"
        note = " The Core group shows the core plugin and only the core skills that project skills declare in `metadata.related`; the core repository has the full graph."
        if extended:
            note += " An arrow labeled extends goes from a project skill to the core skill it extends."
        return render(skills, groups, direction, note, marker=True)
    link(skills)
    return render(skills, groups, direction)


def main(argv: list[str]) -> int:
    project = repo_root(Path(os.environ.get("HARNESS_ROOT") or Path.cwd()).resolve())
    core = repo_root(Path(__file__).resolve().parent)
    text = build(project, core)
    target = project / README
    if "--check" in argv:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != text:
            print(
                f"{README} is out of date. From the project root, run {core / '.agents/scripts/skill-graph/run-graph.sh'}.",
                file=sys.stderr,
            )
            return 1
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
